### ISSUE TITLE
How to install using tinymce-vue?

### ISSUE THREAD

**Issue by staaph** [joostory/tinymce-plugin-codeblock#22]
Hi,

I was trying to integrate the plugin using tinymce and tinymce-vue@^4 with Vue 3 and Vite like this:
`import 'tinymce-plugin-codeblock';` & 
`<editor
      :init="{
        plugins:
          'textarea code visualblocks help image table lists link codeblock',
        toolbar: 'codeblock code',
        codeblock: {
          highlightStyle:
            'https://cdn.jsdelivr.net/highlight.js/9.10.0/styles/default.min.css',
          codeTheme: 'default',
        },
      }"
    />`
However I get the following error: 
'Uncaught Error: Dynamic require of.../node_modules/tinymce-plugin-codeblock/lib/styles/codeblock.css" is not supported'

What is the correct way? Would you consider updating the docs for the plugin?

Thank you

**Comment by joostory** [comment]
Hi,

This plugin needs global tinymce and codemirror. Like this.
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite App</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/highlight.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.3/codemirror.min.js"></script>  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.3/codemirror.min.css">
    <script src="https://cloud.tinymce.com/6/tinymce.min.js"></script>  
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
```

and need vite Commonjs plugin.

```javascript
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { viteCommonjs } from '@originjs/vite-plugin-commonjs'

export default defineConfig({
  plugins: [vue(), viteCommonjs()]
})
```

then use like this.
```javascript
<script setup>
import { ref } from 'vue'
import Editor from '@tinymce/tinymce-vue'
import 'tinymce-plugin-codeblock'
</script>

<template>
  <Editor
    api-key="no-api-key"
    :init="{
      height: 500,
      plugins: ['codeblock'],
      toolbar: 'codeblock',
    }"
  />
</template>

<style scoped>
</style>
```

**Comment by staaph** [comment]
Thank you very much! I will close the issue. :)
